DROP DATABASE IF EXISTS KEYSTONE;

CREATE DATABASE KEYSTONE;

USE KEYSTONE;

CREATE TABLE UTILISATEUR(
   ID_UTILISATEUR INT UNSIGNED NOT NULL AUTO_INCREMENT,
   NOM_UTILISATEUR VARCHAR(50),
   PRENOM_UTILISATEUR VARCHAR(50),
   MAIL_UTILISATEUR VARCHAR(255),
   MOT_DE_PASSE_UTILISATEUR VARCHAR(255),
   PRIMARY KEY(ID_UTILISATEUR)
) ENGINE = INNODB;

CREATE TABLE ADMINISTRATEUR(
   ID_ADMIN SMALLINT,
   NOM_ADMIN VARCHAR(50),
   PRENOM_ADMIN VARCHAR(50),
   MAIL_ADMIN VARCHAR(255),
   MOT_DE_PASSE_ADMIN VARCHAR(255),
   PRIMARY KEY(ID_ADMIN)
) ENGINE = INNODB;

CREATE TABLE IMAGE(
   ID_IMAGE BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
   DESCRIPTION_IMAGE VARCHAR(255),
   VILLE_IMAGE VARCHAR(50),
   PAYS_IMAGE VARCHAR(50),
   CODE_POSTAL_IMAGE INT,
   NOM_IMAGE VARCHAR(255),
   PRIMARY KEY(ID_IMAGE),
   UNIQUE(NOM_IMAGE)
) ENGINE = INNODB;

CREATE TABLE POSSEDER(
   ID_UTILISATEUR INT UNSIGNED NOT NULL,
   ID_IMAGE BIGINT UNSIGNED NOT NULL,
   PRIMARY KEY(ID_UTILISATEUR, ID_IMAGE),
   FOREIGN KEY(ID_UTILISATEUR) REFERENCES UTILISATEUR(ID_UTILISATEUR),
   FOREIGN KEY(ID_IMAGE) REFERENCES IMAGE(ID_IMAGE)
) ENGINE = INNODB;
